# minigrid_loca env + fifo buffer.
exp_name: minigrid_loca_fifo
array: "0-2"
time: "23:59:59"
profile: minigrid   # mujoco (Reacher) or minigrid
configs: minigrid_loca
overrides:
  replay.variant: fifo
